sudo: required
dist: xenial
language: generic

notifications:
    email: false

before_install:
- sudo apt-get update
- sudo apt-get install wkhtmltopdf make zip

script:
    - make PREFIX="$PWD/output" -C MathAnalysis/Sem4 install
    - make PREFIX="$PWD/output" -C MathLogic/Colloq install
    - zip -r release.zip output
deploy:
        provider: releases
        api_key: $GITHUB_OAUTH_TOKEN
        file:
            - output/Integrals.pdf
            - output/Defs.html
        skip_cleanup: true
        #        on:
        #  tags: true
